import { mkdir, readFile, readdir, stat, writeFile } from "node:fs/promises";
import { relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  OWNER_STATS_COLUMNS,
  TOKEN_COLUMNS,
  holdingsFinalizeSql,
} from "../archive-import/lib/schema.mjs";
import { SqlShardWriter, writeStaticArtifact } from "../archive-import/lib/sql-shards.mjs";
import {
  assertSqliteAvailable,
  jsonObjectSelect,
  queryJsonRows,
  streamJsonRows,
} from "../archive-import/lib/sqlite.mjs";
import {
  describeFile,
  invariant,
  isSafeInteger,
  normalizeAddress,
} from "../archive-import/lib/util.mjs";
import { readJson } from "../collections-backup/lib/files.mjs";
import { SOURCE_UID_DERIVATION } from "./config.mjs";

const PROJECT_ROOT = fileURLToPath(new URL("../../", import.meta.url));
const FORMAT_VERSION = 1;
const GENERATED_HEADER = "-- Generated by tools/compass-holdings. Do not edit.\n\n";
const SOURCE_TOKEN_COLUMNS = [
  "source_uid",
  "poap_id",
  "drop_id",
  "minted_on",
  "owner_address",
  "network",
  "transfer_count",
];
const HOLDING_DROP_COLUMNS = [
  "drop_id",
  "fancy_id",
  "title",
  "description",
  "start_date",
  "end_date",
  "expiry_date",
  "city",
  "country",
  "event_url",
  "year",
  "is_virtual",
  "is_private",
  "is_hidden",
  "channel",
  "platform",
  "location_type",
  "timezone",
  "integrator_id",
  "created_at",
  "image_url",
  "animation_url",
  "token_count",
  "transfer_count",
];
const MIGRATIONS = [
  ["prepare/000001_schema.sql", "migrations/holdings/0001_schema.sql"],
  ["prepare/000002_import_shards.sql", "migrations/holdings/0002_import_shards.sql"],
  ["prepare/000003_drop_collectors.sql", "migrations/holdings/0003_drop_collectors.sql"],
  ["prepare/000004_referenced_drops.sql", "migrations/holdings/0004_referenced_drops.sql"],
];

export async function buildCompassHoldingsD1(options = {}) {
  const settings = normalizeOptions(options);
  const sourceManifestPath = resolve(settings.input, "manifest.json");
  const sourceDatabasePath = resolve(settings.input, "compass-holdings.sqlite");
  const referencedManifestPath = resolve(settings.input, "referenced-drops-manifest.json");
  const referencedDatabasePath = resolve(settings.input, "compass-referenced-drops.sqlite");
  const sourceManifest = await readJson(sourceManifestPath);
  const referencedManifest = await readJson(referencedManifestPath);
  validateSourceManifest(sourceManifest);
  validateReferencedManifest(referencedManifest, sourceManifest);
  await prepareOutput(settings.output);
  const sqliteVersion = await assertSqliteAvailable();

  const [
    sourceManifestArtifact,
    sourceDatabaseArtifact,
    referencedManifestArtifact,
    referencedDatabaseArtifact,
  ] = await Promise.all([
    describeFile(sourceManifestPath),
    describeFile(sourceDatabasePath),
    describeFile(referencedManifestPath),
    describeFile(referencedDatabasePath),
  ]);
  invariant(
    sourceDatabaseArtifact.sha256 === sourceManifest.database.sha256 &&
      sourceDatabaseArtifact.byteLength === sourceManifest.database.byteLength,
    "Compass source database does not match its manifest.",
  );
  invariant(
    referencedDatabaseArtifact.sha256 === referencedManifest.database.sha256 &&
      referencedDatabaseArtifact.byteLength === referencedManifest.database.byteLength,
    "Referenced Drop database does not match its manifest.",
  );
  await validateSourceDatabase(sourceDatabasePath, sourceManifest);
  await validateReferencedDatabase(referencedDatabasePath, referencedManifest);

  const artifacts = [];
  for (const [targetPath, sourcePath] of MIGRATIONS) {
    artifacts.push(
      await writeStaticArtifact(
        settings.output,
        targetPath,
        await readFile(resolve(PROJECT_ROOT, sourcePath), "utf8"),
        {
          kind: "d1-sql",
          phase: "prepare",
          database: "holdings",
        },
      ),
    );
  }

  const journal = {
    snapshotId: sourceManifest.snapshotId,
    sourceDatabaseSha256: sourceDatabaseArtifact.sha256,
  };
  const tokenWriter = makeSqlWriter(settings, {
    sequenceStart: 100_001,
    label: "tokens",
    table: "tokens",
    columns: TOKEN_COLUMNS,
    journal,
  });
  const ownerWriter = makeSqlWriter(settings, {
    sequenceStart: 800_001,
    label: "owner_stats",
    table: "owner_stats",
    columns: OWNER_STATS_COLUMNS,
    journal,
  });
  const holdingDropWriter = makeSqlWriter(settings, {
    sequenceStart: 900_001,
    label: "holding_drops",
    table: "holding_drops",
    columns: HOLDING_DROP_COLUMNS,
    journal,
  });

  let tokenCount = 0;
  let ownerCount = 0;
  let owner = null;
  const networks = new Map();
  const dropStats = new Map();
  const flushOwner = async () => {
    if (!owner) return;
    const row = [
      owner.address,
      owner.tokenCount,
      owner.dropIds.size,
      owner.firstMintedOn,
      owner.lastMintedOn,
    ];
    validateOwnerRow(row);
    await ownerWriter.add(row);
    ownerCount += 1;
    owner = null;
  };

  for await (const row of streamJsonRows(
    sourceDatabasePath,
    jsonObjectSelect("tokens", SOURCE_TOKEN_COLUMNS, {
      orderBy: "lower(owner_address), poap_id DESC, source_uid DESC",
    }),
  )) {
    const normalizedAddress = normalizeAddress(row.owner_address);
    validateTokenRow(row, normalizedAddress);
    if (owner?.address !== normalizedAddress) {
      await flushOwner();
      owner = {
        address: normalizedAddress,
        tokenCount: 0,
        dropIds: new Set(),
        firstMintedOn: row.minted_on,
        lastMintedOn: row.minted_on,
      };
    }
    owner.tokenCount += 1;
    owner.dropIds.add(row.drop_id);
    owner.firstMintedOn = Math.min(owner.firstMintedOn, row.minted_on);
    owner.lastMintedOn = Math.max(owner.lastMintedOn, row.minted_on);
    networks.set(row.network, (networks.get(row.network) ?? 0) + 1);
    const drop = dropStats.get(row.drop_id) ?? { tokenCount: 0, transferCount: 0 };
    drop.tokenCount += 1;
    drop.transferCount += row.transfer_count;
    dropStats.set(row.drop_id, drop);
    await tokenWriter.add([
      row.source_uid,
      row.poap_id,
      row.drop_id,
      row.minted_on,
      normalizedAddress,
      row.network,
      row.transfer_count,
    ]);
    tokenCount += 1;
    if (tokenCount % 500_000 === 0) {
      settings.onProgress({
        phase: "build-d1",
        tokens: tokenCount,
        expected: sourceManifest.counts.captured,
      });
    }
  }
  await flushOwner();
  let holdingDropCount = 0;
  for await (const row of streamJsonRows(
    referencedDatabasePath,
    `SELECT json_object(
      'drop_id', d.drop_id,
      'fancy_id', d.fancy_id,
      'title', d.title,
      'description', d.description,
      'start_date', d.start_date,
      'end_date', d.end_date,
      'expiry_date', m.expiry_date,
      'city', d.city,
      'country', d.country,
      'event_url', d.event_url,
      'year', d.year,
      'is_virtual', d.is_virtual,
      'is_private', d.is_private,
      'is_hidden', m.is_hidden,
      'channel', d.channel,
      'platform', d.platform,
      'location_type', d.location_type,
      'timezone', d.timezone,
      'integrator_id', m.integrator_id,
      'created_at', d.created_at,
      'image_url', m.image_url,
      'animation_url', m.animation_url
    )
    FROM drops d
    JOIN compass_drop_metadata m ON m.drop_id = d.drop_id
    ORDER BY d.drop_id`,
  )) {
    const stats = dropStats.get(row.drop_id);
    invariant(stats, `Referenced Drop ${row.drop_id} has no Holdings rows.`);
    row.token_count = stats.tokenCount;
    row.transfer_count = stats.transferCount;
    validateHoldingDropRow(row);
    const values = HOLDING_DROP_COLUMNS.map((column) => row[column]);
    await holdingDropWriter.add(values);
    holdingDropCount += 1;
  }
  artifacts.push(
    ...(await tokenWriter.close()),
    ...(await ownerWriter.close()),
    ...(await holdingDropWriter.close()),
  );
  invariant(tokenCount === sourceManifest.counts.captured, "D1 token count differs from capture.");
  invariant(
    holdingDropCount === referencedManifest.counts.captured,
    "D1 referenced Drop count differs from capture.",
  );
  invariant(
    holdingDropCount + referencedManifest.counts.missing === dropStats.size,
    "Referenced Drop coverage differs from Holdings.",
  );

  const metadata = {
    capture_finished_at: sourceManifest.finishedAt,
    generated_at: new Date().toISOString(),
    importer_version: FORMAT_VERSION,
    owners_count: ownerCount,
    schema_version: 1,
    snapshot_at: sourceManifest.startedAt,
    snapshot_id: sourceManifest.snapshotId,
    source: "poap-compass-public-graphql",
    source_database_sha256: sourceDatabaseArtifact.sha256,
    source_manifest_sha256: sourceManifestArtifact.sha256,
    referenced_drops_count: holdingDropCount,
    referenced_drops_database_sha256: referencedDatabaseArtifact.sha256,
    referenced_drops_manifest_sha256: referencedManifestArtifact.sha256,
    source_uid_derivation: SOURCE_UID_DERIVATION,
    tokens_count: tokenCount,
  };
  artifacts.push(
    await writeStaticArtifact(
      settings.output,
      "finalize/999999_finalize.sql",
      holdingsFinalizeSql(metadata, { generatedHeader: GENERATED_HEADER.trimEnd() }),
      {
        kind: "d1-sql",
        phase: "finalize",
        database: "holdings",
      },
    ),
  );
  const phaseOrder = { prepare: 0, load: 1, finalize: 2 };
  artifacts.sort(
    (left, right) =>
      phaseOrder[left.phase] - phaseOrder[right.phase] || left.path.localeCompare(right.path, "en"),
  );

  const report = {
    version: FORMAT_VERSION,
    dataset: "poapin-compass-holdings-d1",
    snapshotId: sourceManifest.snapshotId,
    source: {
      manifest: {
        path: relative(settings.input, sourceManifestPath).replaceAll("\\", "/"),
        ...sourceManifestArtifact,
      },
      database: {
        path: relative(settings.input, sourceDatabasePath).replaceAll("\\", "/"),
        ...sourceDatabaseArtifact,
      },
      referencedDrops: {
        manifest: {
          path: relative(settings.input, referencedManifestPath).replaceAll("\\", "/"),
          ...referencedManifestArtifact,
        },
        database: {
          path: relative(settings.input, referencedDatabasePath).replaceAll("\\", "/"),
          ...referencedDatabaseArtifact,
        },
        requested: referencedManifest.counts.requested,
        captured: referencedManifest.counts.captured,
        missing: referencedManifest.counts.missing,
      },
      capture: {
        startedAt: sourceManifest.startedAt,
        finishedAt: sourceManifest.finishedAt,
        upperPoapId: sourceManifest.pagination.upperPoapId,
        consistency: sourceManifest.captureWindow.consistency,
      },
    },
    builder: {
      node: process.versions.node,
      sqlite: sqliteVersion,
      settings: {
        maxShardBytes: settings.maxShardBytes,
        maxStatementBytes: settings.maxStatementBytes,
        rowsPerStatement: settings.rowsPerStatement,
      },
    },
    tables: {
      tokens: tokenCount,
      owner_stats: ownerCount,
      drop_collector_refs: tokenCount,
      holding_drops: holdingDropCount,
    },
    networks: Object.fromEntries(
      [...networks.entries()].sort(([left], [right]) => left.localeCompare(right, "en")),
    ),
    metadata,
    artifacts,
  };
  const reportPath = resolve(settings.output, "report.json");
  await writeFile(reportPath, `${JSON.stringify(report, null, 2)}\n`, {
    flag: "wx",
    mode: 0o600,
  });
  return { report, reportPath };
}

async function validateReferencedDatabase(databasePath, manifest) {
  const quickCheck = await queryJsonRows(
    databasePath,
    "SELECT json_object('result', quick_check) FROM pragma_quick_check",
    { maximumRows: 100 },
  );
  invariant(
    quickCheck.length === 1 && quickCheck[0].result === "ok",
    "Referenced Drop SQLite quick_check failed.",
  );
  const [summary] = await queryJsonRows(
    databasePath,
    `SELECT json_object(
      'requested', (SELECT COUNT(*) FROM requested_drops),
      'captured', (SELECT COUNT(*) FROM requested_drops WHERE captured = 1),
      'drops', (SELECT COUNT(*) FROM drops),
      'metadata', (SELECT COUNT(*) FROM compass_drop_metadata),
      'invalid', (
        SELECT COUNT(*)
        FROM drops d
        JOIN compass_drop_metadata m ON m.drop_id = d.drop_id
        WHERE d.drop_id <= 0
          OR d.fancy_id IS NULL
          OR d.title IS NULL
          OR d.start_date IS NULL
          OR d.end_date IS NULL
          OR d.year IS NULL
          OR d.is_private NOT IN (0, 1)
          OR m.is_hidden NOT IN (0, 1)
          OR d.created_at IS NULL
      )
    )`,
    { maximumRows: 1 },
  );
  invariant(summary?.requested === manifest.counts.requested, "Requested Drop count differs.");
  invariant(summary?.captured === manifest.counts.captured, "Captured Drop count differs.");
  invariant(summary?.drops === manifest.counts.captured, "Referenced Drop rows differ.");
  invariant(summary?.metadata === manifest.counts.captured, "Referenced metadata rows differ.");
  invariant(summary?.invalid === 0, "Referenced Drop database has invalid rows.");
}

async function validateSourceDatabase(databasePath, manifest) {
  const quickCheck = await queryJsonRows(
    databasePath,
    "SELECT json_object('result', quick_check) FROM pragma_quick_check",
    { maximumRows: 100 },
  );
  invariant(
    quickCheck.length === 1 && quickCheck[0].result === "ok",
    "Compass source SQLite quick_check failed.",
  );
  const [summary] = await queryJsonRows(
    databasePath,
    `SELECT json_object(
      'tokens', COUNT(*),
      'invalidDropIds', SUM(drop_id IS NULL OR drop_id <= 0),
      'invalidMintedOn', SUM(minted_on IS NULL OR minted_on < 0),
      'invalidNetworks', SUM(network IS NULL OR length(network) = 0),
      'invalidTransfers', SUM(transfer_count IS NULL OR transfer_count < 0),
      'invalidOwners', SUM(
        length(owner_address) <> 42
        OR substr(owner_address, 1, 2) <> '0x'
        OR substr(owner_address, 3) GLOB '*[^0-9a-f]*'
        OR owner_address <> lower(owner_address)
      )
    ) FROM tokens`,
    { maximumRows: 1 },
  );
  invariant(summary?.tokens === manifest.counts.captured, "Capture database row count differs.");
  for (const key of [
    "invalidDropIds",
    "invalidMintedOn",
    "invalidNetworks",
    "invalidTransfers",
    "invalidOwners",
  ]) {
    invariant(summary[key] === 0, `Capture database has ${summary[key]} ${key} rows.`);
  }
}

function validateSourceManifest(manifest) {
  invariant(manifest?.version === 1, "Unsupported Compass Holdings manifest version.");
  invariant(
    manifest.dataset === "poapin-compass-holdings",
    "Input is not a Compass Holdings snapshot.",
  );
  invariant(
    /^[a-z0-9][a-z0-9._-]{0,63}$/.test(manifest.snapshotId ?? ""),
    "Compass snapshot ID is invalid.",
  );
  invariant(
    Number.isSafeInteger(manifest.counts?.captured) &&
      manifest.counts.captured > 0 &&
      manifest.counts.captured === manifest.counts.expected,
    "Compass snapshot is incomplete.",
  );
  invariant(
    /^[0-9a-f]{64}$/.test(manifest.database?.sha256 ?? "") &&
      Number.isSafeInteger(manifest.database?.byteLength) &&
      manifest.database.byteLength > 0,
    "Compass source database descriptor is invalid.",
  );
}

function validateReferencedManifest(manifest, sourceManifest) {
  invariant(manifest?.version === 1, "Unsupported referenced Drop manifest version.");
  invariant(
    manifest.dataset === "poapin-compass-referenced-drops",
    "Input is not a referenced Drop capture.",
  );
  invariant(manifest.snapshotId === sourceManifest.snapshotId, "Referenced Drop snapshot differs.");
  invariant(
    Number.isSafeInteger(manifest.counts?.requested) &&
      Number.isSafeInteger(manifest.counts?.captured) &&
      Number.isSafeInteger(manifest.counts?.missing) &&
      manifest.counts.requested > 0 &&
      manifest.counts.captured > 0 &&
      manifest.counts.captured + manifest.counts.missing === manifest.counts.requested,
    "Referenced Drop capture counts are invalid.",
  );
}

function validateTokenRow(row, normalizedAddress) {
  invariant(
    typeof row.source_uid === "string" && row.source_uid.length > 0 && row.source_uid.length <= 128,
    `Invalid source UID ${row.source_uid ?? "<missing>"}.`,
  );
  invariant(isSafeInteger(row.poap_id, { minimum: 1 }), `Invalid POAP ${row.poap_id}.`);
  invariant(isSafeInteger(row.drop_id, { minimum: 1 }), `POAP ${row.poap_id} has no Drop.`);
  invariant(isSafeInteger(row.minted_on, { minimum: 0 }), `POAP ${row.poap_id} has no mint time.`);
  invariant(normalizedAddress !== null, `POAP ${row.poap_id} has an invalid owner.`);
  invariant(
    typeof row.network === "string" && row.network.length > 0,
    `POAP ${row.poap_id} has an invalid network.`,
  );
  invariant(
    isSafeInteger(row.transfer_count, { minimum: 0 }),
    `POAP ${row.poap_id} has an invalid transfer count.`,
  );
}

function validateOwnerRow(row) {
  invariant(normalizeAddress(row[0]) === row[0], "Owner aggregate address is invalid.");
  invariant(isSafeInteger(row[1], { minimum: 1 }), "Owner token count is invalid.");
  invariant(isSafeInteger(row[2], { minimum: 1 }), "Owner unique Drop count is invalid.");
  invariant(isSafeInteger(row[3], { minimum: 0 }), "Owner first mint time is invalid.");
  invariant(isSafeInteger(row[4], { minimum: row[3] }), "Owner last mint time is invalid.");
}

function validateHoldingDropRow(row) {
  invariant(isSafeInteger(row.drop_id, { minimum: 1 }), "Referenced Drop ID is invalid.");
  for (const column of ["fancy_id", "title", "start_date", "end_date", "created_at"]) {
    invariant(
      typeof row[column] === "string",
      `Referenced Drop ${row.drop_id} ${column} is invalid.`,
    );
  }
  invariant(isSafeInteger(row.year), `Referenced Drop ${row.drop_id} year is invalid.`);
  invariant(
    row.is_virtual === null || row.is_virtual === 0 || row.is_virtual === 1,
    `Referenced Drop ${row.drop_id} virtual value is invalid.`,
  );
  invariant(
    (row.is_private === 0 || row.is_private === 1) && (row.is_hidden === 0 || row.is_hidden === 1),
    `Referenced Drop ${row.drop_id} visibility is invalid.`,
  );
  invariant(
    isSafeInteger(row.token_count, { minimum: 0 }) &&
      isSafeInteger(row.transfer_count, { minimum: 0 }),
    `Referenced Drop ${row.drop_id} aggregate is invalid.`,
  );
}

function makeSqlWriter(settings, config) {
  return new SqlShardWriter({
    outputRoot: settings.output,
    relativeDirectory: "load",
    maxShardBytes: settings.maxShardBytes,
    maxStatementBytes: settings.maxStatementBytes,
    rowsPerStatement: settings.rowsPerStatement,
    database: "holdings",
    generatedHeader: GENERATED_HEADER,
    ...config,
  });
}

async function prepareOutput(output) {
  try {
    const outputStat = await stat(output);
    invariant(outputStat.isDirectory(), `D1 output is not a directory: ${output}`);
    invariant((await readdir(output)).length === 0, `D1 output is not empty: ${output}`);
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
    await mkdir(output, { recursive: true });
  }
}

function normalizeOptions(options) {
  invariant(typeof options.input === "string" && options.input.length > 0, "input is required.");
  const input = resolve(options.input);
  const output = resolve(options.output ?? input, options.output ? "" : "d1");
  const maxShardBytes = options.maxShardBytes ?? 8 * 1024 * 1024;
  const maxStatementBytes = options.maxStatementBytes ?? 90 * 1024;
  const rowsPerStatement = options.rowsPerStatement ?? 100;
  invariant(
    Number.isSafeInteger(maxShardBytes) && maxShardBytes >= maxStatementBytes,
    "maxShardBytes is invalid.",
  );
  invariant(
    Number.isSafeInteger(maxStatementBytes) &&
      maxStatementBytes > 0 &&
      maxStatementBytes <= 96 * 1024,
    "maxStatementBytes is invalid.",
  );
  invariant(
    Number.isSafeInteger(rowsPerStatement) && rowsPerStatement > 0,
    "rowsPerStatement is invalid.",
  );
  return {
    input,
    output,
    maxShardBytes,
    maxStatementBytes,
    rowsPerStatement,
    onProgress: options.onProgress ?? (() => {}),
  };
}

export const d1Internals = {
  normalizeOptions,
  validateOwnerRow,
  validateSourceManifest,
  validateTokenRow,
};
